# Shared mgmt-cluster Nexus integration defaults.
# Documentation: see docs/variables.md
# Variable ownership overview: docs/variables.md

---
backup_dir: "/home/ansible/backup"
#
mgmt_cluster1_PC:
  - interface: "port-channel47"
    # id must be same as port-channel number
    id: "47"
    speed: "auto"
    duplex: "auto"
    description: "Uplink-mgmt-cluster-1"
#
mgmt_cluster2_PC:
  - interface: "port-channel48"
    # id must be same as port-channel number
    id: "48"
    speed: "auto"
    duplex: "auto"
    description: "Uplink-mgmt-cluster-2"
#
mgmt_cluster_port_channels: "{{ mgmt_cluster1_PC + mgmt_cluster2_PC }}"
#

#
# Define list of VLANs configured on mgmt-cluster ports.
# t_all_vlans_list is only used with TENANT.yml - to avoid an error with INFRA.yml the defaul(all_vlans_list) is used.
#
vlans_list: "{{ all_vlans_list }},{{ sg_vlans_list }},{{ t_all_vlans_list|default(all_vlans_list) }}"
#
