---
  # This task updates the allowed VLANs list on the VPC Peer-Lin

  - name: Get configured VLAN list from Peer-Link Port-Channel
    cisco.nxos.nxos_command:
      commands:
        - show run int port-channel53
    register: current_config
    

  - name: Parse running configuration
    cisco.nxos.nxos_l2_interfaces:
      running_config: "{{ current_config.stdout[0] }}"
      state: parsed
    register: parsed_config

  - name: Create list of required VLANs
    set_fact:
      update_vlans: "{{ parsed_config.parsed[0].trunk.allowed_vlans }},{{ sg_vlans_list }}"

  - name: Enabling StorageGRID vlans on VPC Peer-Link
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ update_vlans }}"
    with_list: "{{ peerlink_PC }}"
#
