---
# Create and Deploy the server profile template(s). Users can derive one or more server profiles
# from these templates

- name: "Create Server Profile Templates"
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/dataspace.yml
    - group_vars/ucs.yml
    - group_vars/ucs_dataspace.yml

  # Create Server PoProfile Templates
  roles:
    - role: UCS-IMM/create_server_profile_template
