---
#Execute the below ONTAP Role after UCS playbook
- name: Configure ONTAP Boot Storage Setup
  hosts: ontap
  gather_facts: False
  vars_files:
    - vars/ontap_main.yml
    - group_vars/all.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_luns, tags: [ 'ontap_luns' ] }
  tags:
  - ontap_config_part_2
  - flexpod_config
