---
#Execute the below ONTAP Role after Nexus playbook
- name: Configure ONTAP for FlexPod
  hosts: ontap
  gather_facts: False
  vars:
    state: present
  vars_files:
    - vars/ontap_main_XX.yml
    - group_vars/all.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_svm_custom, tags: [ 'ontap_svm', 'create_svm_custom' ] }
    # - { role: ONTAP/ontap_lifs, tags: [ 'ontap_lifs' ] }
