---
- name: Testing play
  hosts: rke2_servers
  become: yes
  gather_facts: no
  roles:
    - role: rancher/env_vars
    - role: rancher/pre_rke_install
#
# Setup RKE2 Control-Nodes or Control-/Agent-Nodes
#
- name: Install RKE2 Server
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/env_vars
    - role: rancher/rke2_server
  serial: 1
  environment:
    http_proxy: http://172.16.4.12:81
    https_proxy: http://172.16.4.12:81

#
# Setup RKE2 dedicated Agent-Nodes
#
- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/rke2_agent
  serial: 3
#
