---
# 
# This Playbook sets up a physical Tenant on FlexPod, configuring Nexus switches, NetApp storage and UCS profiles.
#
# Configure VLANs, VRF, and IP addresses for the tenant
- hosts: nexus
  connection: network_cli
  gather_facts: no
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/nexus_config, tags: [ 'nexus_vlan' ] }
  - { role: TENANT/nexus_config_ip, tags: [ 'gpusystem' ] }
  tags:
  - nexus_config
  - hardware_tenant

# Configure VLANs, LIFs, SVM, and LUNs for the tenant
- name: Configure ONTAP for FlexPod
  hosts: ontap
    #serial: 1
  gather_facts: False
  connection: local
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/ontap_network, tags: [ 'ontap_network' ] }
  - { role: TENANT/ontap_svm, tags: [ 'ontap_svm' ] }
  - { role: TENANT/ontap_volumes, tags: [ 'ontap_volumes' ] }
  - { role: TENANT/ontap_lifs, tags: [ 'ontap_lifs' ] }
  - { role: TENANT/ontap_luns, tags: [ 'ontap_luns' ] }
  # - { role: TENANT/ontap_nvme, tags: [ 'ontap_nvme' ] }
  tags:
  - ontap_config
  - flexpod_config
  - hardware_tenant

# Get iSCSI IQN from SVM
#- name: Gather iSCSI IQN from SVM
#  hosts: ontap
#  gather_facts: False
#  connection: local
#  roles:
#  - { role: TENANT/env_vars }
#  - { role: TENANT/ontap_iqn, tags: [ 'ontap_network' ] }
#  tags:
#  - ontap_config_part_2
#  - hardware_tenant

# Create various pools, policies, and a server profile template
#
- name: "Create Tenant in Intersight "
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/ucs.yml
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/ucs_create_pools }
  - { role: TENANT/ucs_create_server_policies }
  - { role: TENANT/ucs_create_sp_template }
  tags:
  - ucs_config
  - flexpod_config
  - hardware_tenant


#Execute the below ONTAP Role after installing and configuring ESXi Hosts
#- name: Configure ONTAP NVMe Setup and finalize ONTAP storage
#  hosts: ontap
#  gather_facts: False
#  connection: local
#  roles:
#  - { role: TENANT/env_vars }
#    #  - { role: TENANT/ontap_nvme, tags: [ 'ontap_nvme' ] }
#  - { role: TENANT/ontap_finalize_setup, tags: [ 'ontap_finalize_setup' ]}
#  tags:
#  - ontap_config_part_2
#  - flexpod_config
#  - hardware_tenant

# This Playbook sets up both Nexus switches for Ethernet switching in FlexPod
# After executing this playbook, LAN connectivity should be configured
#
- hosts: nexus
  connection: network_cli
  gather_facts: no
  vars_files:
    - group_vars/storagegrid.yml
    - group_vars/proxmox.yml

  roles:
    ### Configure Nexus Switching
    #
    - TENANT/nexus_config_proxmox
    #
  tags:
  - proxmox_config
  - hardware_tenant

#
# Prepare RKE2 Install behind proxy Server
#
- name: Prepare installation of Rancher RKE2 control nodes
  hosts: rke2_servers,rke2_agents
  become: yes
  gather_facts: no
  roles:
    - role: rancher/env_vars
    - role: rancher/pre_rke_install
  tags:
  - rke_install
#
# Setup RKE2 Control-Nodes or Control-/Agent-Nodes
#
- name: Install RKE2 Controll node server
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/env_vars
    - role: rancher/rke2_server
  serial: 1
  environment:
    http_proxy: http://172.16.4.12:81
    https_proxy: http://172.16.4.12:81
  tags:
  - rke_install

#
# Setup RKE2 dedicated Agent-Nodes
#
- name: Install RKE2 dedicated agent nodes
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/rke2_agent
  serial: 3
  tags:
  - rke_install
#

# Configure Astra Trident on K8s cluster and the storage backend
- name: Deploy NetApp Trident and Configure Trident Backend
  hosts: k8s
    #serial: 1
  gather_facts: False
  connection: local
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/trident_install, tags: [ 'trident_install' ] }
  tags:
  - trident_install

