---
#
# This Playbook sets up a physical Tenant on FlexPod, configuring Nexus switches, NetApp storage and UCS profiles.
#
# Configure VLANs, VRF, and IP addresses for the tenant
- hosts: nexus
  connection: network_cli
  gather_facts: no
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/nexus_config }
  - { role: TENANT/nexus_config_ip }
  - { role: TENANT/nexus_config_sg }
  - { role: TENANT/nexus_config_asa }
  tags:
  - nexus_config
  - hardware_tenant

# Configure VLANs, LIFs, SVM, and LUNs for the tenant
- name: Configure ONTAP for FlexPod
  hosts: ontap
    #serial: 1
  gather_facts: False
  connection: local
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/ontap_network, tags: [ 'ontap_network' ], when: not ansible_check_mode }
  - { role: TENANT/ontap_svm, tags: [ 'ontap_svm' ], when: not ansible_check_mode }
  - { role: TENANT/ontap_volumes, tags: [ 'ontap_volumes' ], when: not ansible_check_mode }
  - { role: TENANT/ontap_lifs, tags: [ 'ontap_lifs' ], when: not ansible_check_mode }
  - { role: TENANT/ontap_luns, tags: [ 'ontap_luns' ], when: not ansible_check_mode }
  - { role: TENANT/ontap_nvme, tags: [ 'ontap_nvme' ], when: not ansible_check_mode }
  tags:
  - ontap_config
  - flexpod_config
  - hardware_tenant

# Create various pools, policies, and a server profile template
#
- name: Create Tenant in Intersight
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/ucs.yml
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/ucs_create_pools, when: not ansible_check_mode }
  - { role: TENANT/ucs_create_server_policies, when: not ansible_check_mode }
  - { role: TENANT/ucs_create_sp_template, when: not ansible_check_mode }
    #  - { role: TENANT/ucs_create_server }
  tags:
  - ucs_config
  - flexpod_config
  - hardware_tenant


#Execute the below ONTAP Role after installing and configuring ESXi Hosts
#- name: Configure ONTAP NVMe Setup and finalize ONTAP storage
#  hosts: ontap
#  gather_facts: False
#  connection: local
#  roles:
#  - { role: TENANT/env_vars }
#    #  - { role: TENANT/ontap_nvme, tags: [ 'ontap_nvme' ] }
#  - { role: TENANT/ontap_finalize_setup, tags: [ 'ontap_finalize_setup' ]}
#  tags:
#  - ontap_config_part_2
#  - flexpod_config
#  - hardware_tenant

#
# Create Server Profiles from Template
#
- name: Create Server Profiles from Template
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/ucs.yml
  roles:
    - role: TENANT/env_vars
    - role: TENANT/ucs_create_server
      when: not ansible_check_mode
  tags:
  - os_install


#
# Install SUSE Linux
#
- name: Install SUSE Linux
  hosts: rke2_servers,rke2_agents,hosts
  become: yes
  gather_facts: no
  roles:
    - role: TENANT/env_vars
    - role: TENANT/os_install_suse
      when: not ansible_check_mode
  tags:
  - os_install

#
# Prepare RKE2 Install behind proxy Server
#
- name: Prepare installation of Rancher RKE2 control nodes
  hosts: rke2_servers,rke2_agents
  become: yes
  gather_facts: no
  roles:
    - role: rancher/env_vars
    - role: rancher/pre_rke_install
      when: not ansible_check_mode
  tags:
  - rke_install
#
# Setup RKE2 Control-Nodes or Control-/Agent-Nodes
#
- name: Install RKE2 Controll node server
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/env_vars
    - role: rancher/rke2_server
      when: not ansible_check_mode
  serial: 1
  environment:
    http_proxy: http://172.16.4.12:81
    https_proxy: http://172.16.4.12:81
  tags:
  - rke_install

#
# Setup RKE2 dedicated Agent-Nodes
#
- name: Install RKE2 dedicated agent nodes
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rancher/rke2_agent
      when: not ansible_check_mode
  serial: 3
  tags:
  - rke_install
#
# Configure Astra Trident on K8s cluster and the storage backend
- name: Deploy NetApp Trident and Configure Trident Backend
  hosts: k8s
    #serial: 1
  gather_facts: False
  connection: local
  roles:
  - { role: TENANT/env_vars }
  - { role: TENANT/trident_install, tags: [ 'trident_install' ], when: not ansible_check_mode }
  tags:
  - trident_install
