---
  # Configuration for Nexus
  #
  # Configure Inerface, Port-Channel and Trunk Settings
  - include_tasks: set_nxos_interfaces.yml
  # Configure VLANs on Peer-Link
  - include_tasks: update_peer_link.yml
