env_vars_directory: "{{ playbook_dir }}/customconfig"  # custom configs
env_vars_all_file: "{{ playbook_dir }}/group_vars/all.yml"
env_vars_ucs_file: "{{ playbook_dir }}/group_vars/ucs.yml"
env_vars_ontap_file: "{{ playbook_dir }}/group_vars/ontap.yml"
env_vars_sg_file: "{{ playbook_dir }}/group_vars/storagegrid.yml"
env_vars_proxmox_file: "{{ playbook_dir }}/group_vars/proxmox.yml"
