---
  # Configuration for Nexus
  #
  # Initiate a configuration backup before making changes. The backup will be
  # stored in the  ~/ directory. Change the directory in ../defaults/main.yml
  #  - include_tasks: initiate_nxos_config_backup.yml
  #
  # Create VRFs
  - include_tasks: create_vrf.yml
  # Configure SVI interfaces for L3 support and add them to the required VRF
  - include_tasks: set_nxos_interfaces.yml
  # Save Configuration
  #- include_tasks: save_nxos_config.yml
