---
  # This task creates SVI interface
  - name: Create SVI Interfaces for L3 support
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Vlan{{ item.name }}
    with_list: "{{ t_svi_list }}"

  # This task enables the new SVI interface
  - name: Enable SVI Interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: Vlan{{ item.name }}
        enabled: true
    with_list: "{{ t_svi_list }}"

  # This task adds ports to the SMT-Tenant VRF context
  - name: Add SVI Interfaces to VRF
    cisco.nxos.nxos_vrf_interface:
      vrf: "{{ item.vrf }}"
      interface: Vlan{{ item.name }}
    with_list: "{{ t_svi_list }}"
    when: SMT == true

  # This task adds ports to the Tenant VRF context
  - name: Add SVI Interfaces to VRF
    cisco.nxos.nxos_vrf_interface:
      vrf: "{{ tenant_name|lower }}"
      interface: Vlan{{ item.name }}
    with_list: "{{ t_svi_list }}"
    when: SMT != true

  # This task configures IP address on SVI
  - name: Add IP address to SVI Interfaces for L3 support
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Vlan{{ item.name }}
        ipv4:
        - address: "{{ item.address }}"
    with_list: "{{ t_svi_list }}"

  # This task configures HSRP IP address on SVI
  - name: Add HSRP IP address to SVI Interfaces
    cisco.nxos.nxos_hsrp:
      interface: Vlan{{ item.name }}
      group: "{{ tid }}"
      vip: "{{ item.hsrp }}"
    with_list: "{{ t_svi_list }}"

  # This task enables the new SVI interface
  - name: Enable SVI Interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: Vlan{{ item.name }}
        enabled: true
    with_list: "{{ t_svi_list }}"
