env_vars_env_name: "{{ tenant }}"  # to be set by playbook
#env_vars_directory: "{{ playbook_dir }}/tenant_vars"  # custom configs
#env_vars_common_file: "{{ env_vars_directory }}/default.yml"
#env_vars_tenant_file: "{{ env_vars_directory }}/{{ env_vars_env_name }}.yml"
env_vars_all_file: "{{ playbook_dir }}/group_vars/all.yml"
tenant_dir: "{{ tenants_dir }}/{{ tenant|lower }}"
env_vars_tenant_file: "{{ tenant_dir }}/vars.yml"


