---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: Add audit policy configuration file
  ansible.builtin.copy:
    src: "{{ audit_policy_config_file_path }}"
    dest: "/etc/rancher/rke2/audit-policy.yaml"
    mode: '0640'
    owner: root
    group: root
