---

- name: RKE2 agent and server tasks
  vars:
    rke2_common_caller_role_name: server
  ansible.builtin.include_role:
    name: rancher/rke2_common
    tasks_from: main

- name: Setup initial server
  ansible.builtin.include_tasks: first_server.yml
  when: inventory_hostname in groups['rke2_servers'][0]

- name: Setup other servers
  ansible.builtin.include_tasks: other_servers.yml
  when: inventory_hostname in groups['rke2_servers'][1:]
