---
# This Playbook sets up both Nexus switches for Ethernet switching in FlexPod
# After executing this playbook, LAN connectivity should be configured
#
- hosts: nexus
  connection: network_cli
  gather_facts: no
  vars_files:
    - group_vars/all.yml
  roles:
    ### Configure Nexus Switching
    #
  - { role: NEXUSconfig }
  - { role: NEXUSconfigIP }
    #
  tags:
  - nexus_config
  - flexpod_config

#Execute the below ONTAP Role after Nexus playbook
- name: Configure ONTAP for FlexPod
  hosts: ontap
  gather_facts: False
  vars_files:
    - vars/ontap_main.yml
    - group_vars/all.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_primary_setup, tags: [ 'ontap_primary_setup' ] }
  - { role: ONTAP/ontap_network, tags: [ 'ontap_network' ] }
  - { role: ONTAP/ontap_svm, tags: [ 'ontap_svm' ] }
  - { role: ONTAP/ontap_volumes, tags: [ 'ontap_volumes' ] }
  - { role: ONTAP/ontap_lifs, tags: [ 'ontap_lifs' ] }
  - { role: ONTAP/esxi_datastores, tags: [ 'esxi_datastores' ] }
  tags:
  - ontap_config_part_1
  - flexpod_config

# Create various pools. The pools being created are:
# - IP Pools for Mgmt
# - IQN Pools for iSCSI (if needed)
# - iSCSI IP pools (if needed)
# - WWxx Pools for FC (if needed)
# - UUID pools
# - MAC address Pools
#
- name: "Create Various Pools and Policies"
  hosts: localhost
  gather_facts: no
  vars_files:   # Keep group_vars/ucs.yml always as the first line and the tenant one as second.
    - group_vars/ucs.yml
  # Create Various Pool
  roles:
    - { role: UCS-IMM/create_pools }
    - { role: UCS-IMM/create_server_policies }
  tags:
  - ucs_config
  - flexpod_config

#Execute the below ONTAP Role after UCS playbook
- name: Configure ONTAP Boot Storage Setup
  hosts: ontap
  gather_facts: False
  vars_files:
    - vars/ontap_main.yml
    - group_vars/all.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_luns, tags: [ 'ontap_luns' ] }
  - { role: ONTAP/ontap_nvme, tags: [ 'ontap_nvme' ] }
  - { role: ONTAP/ontap_finalize_setup, tags: [ 'ontap_finalize_setup' ]}
  tags:
  - ontap_config_part_2
  - flexpod_config
