---
- name: "LINUX: Configure LAN Connectivity Policy for local disk boot"
  vars:
    api_info: &api_info_local
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  block:
  - name: "LINUX: LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
          <<: *api_info_local
          resource_path: /vnic/LanConnectivityPolicies
          query_params:
             $filter: "Name eq '{{ name_of_lan_connectivity_policy }}'"
          api_body: {
              "Name": "{{ name_of_lan_connectivity_policy }}",
              "Description": "{{ description_of_lan_connectivity_policy }}",

              "TargetPlatform": "FIAttached",
              "AzureQosEnabled": false,
              "IqnAllocationType": "Pool",
              "PlacementMode": "custom",
              "IqnPool": "{{ iqn_pool_details.api_response.Moid }}",
              "StaticIqnName": "",

              "Organization": {
                 "Moid": "{{ intersight_org.api_response.Moid }}"
               },
              Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}] 
           }
    register: lan_connectivity_policy
#
  - name: "LINUX: Add {{ name_of_vnic_1a }} to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_local
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_1a }}'"
        api_body: {
             "Name": "{{ name_of_vnic_1a }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
             "Placement": {
                "AutoPciLink": true,
                "AutoSlotId": true,                
                "SwitchId": "A"
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ mgmt_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 0
         }
    when: ( name_of_vnic_1 is defined )
#
  - name: "LINUX: Add {{ name_of_vnic_1b }} to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_local
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_1b }}'"
        api_body: {
             "Name": "{{ name_of_vnic_1b }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
             "Placement": {
                "AutoPciLink": true,
                "AutoSlotId": true,                
                "SwitchId": "B"
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ mgmt_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 1
         }
    when: ( name_of_vnic_1 is defined )
#
  - name: "LINUX: Add {{ name_of_vnic_2 }}_A to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_local
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_2 }}_A'"
      api_body: {
           "Name": "{{ name_of_vnic_2 }}_A",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "AutoPciLink": true,
              "AutoSlotId": true,
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ access_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
           "Order": 2          
       }
#
  - name: "LINUX: Add {{ name_of_vnic_2 }}_B to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_local
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_2 }}_B'"
      api_body: {
           "Name": "{{ name_of_vnic_2 }}_B",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
           "Placement": {
              "AutoPciLink": true,
              "AutoSlotId": true,
              "SwitchId": "B"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ access_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
           "Order": 3          
       }
#
  - name: "LINUX: Add {{ name_of_vnic_3 }}_A to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_local
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_3 }}_A'"
        api_body: {
             "Name": "{{ name_of_vnic_3 }}_A",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
             "Placement": {
                "AutoPciLink": true,
                "AutoSlotId": true,                
                "SwitchId": "A"
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ storage_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 4
         }
    when: ( name_of_vnic_3 is defined )
#
  - name: "LINUX: Add {{ name_of_vnic_3 }}_B to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_local
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_3 }}_B'"
        api_body: {
             "Name": "{{ name_of_vnic_3 }}_B",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
             "Placement": {
                "AutoPciLink": true,
                "AutoSlotId": true,                
                "SwitchId": "B"
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ storage_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 5
         }
    when: ( name_of_vnic_3 is defined )

#
  - name: "LINUX: Add {{ name_of_vnic_4 }}_A to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_local
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_4 }}_A'"
      api_body: {
           "Name": "{{ name_of_vnic_4 }}_A",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
           "Placement": {
              "AutoPciLink": true,
              "AutoSlotId": true,
              "SwitchId": "A"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ wan_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
           "Order": 3          
       }
    when: ( name_of_vnic_4 is defined )
#
  - name: "LINUX: Add {{ name_of_vnic_4 }}_B to LAN Connectivity Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info_local
      resource_path: /vnic/EthIfs
      query_params:
         $filter: "Name eq '{{ name_of_vnic_4 }}_B'"
      api_body: {
           "Name": "{{ name_of_vnic_4 }}_B",
           "MacAddressType": "POOL",
           "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
           "Placement": {
              "AutoPciLink": true,
              "AutoSlotId": true,
              "SwitchId": "B"
           },
           "Cdn": {
              "Source": "vnic"
           },
           "FailoverEnabled": false,
           "FabricEthNetworkGroupPolicy": [ "{{ wan_network_group_policy.api_response.Moid }}" ],
           "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
           "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
           "EthAdapterPolicy": "{{ ethernet_adapter_linux_policy.api_response.Moid }}",
           "StaticMacAddress": "",
           "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
           "Order": 3          
       }
    when: ( name_of_vnic_4 is defined )
  when: ( os_bond == 'true' )
