---
# Create Management Broadcast Domain
- name: Create Management Broadcast Domain
  netapp.ontap.na_ontap_broadcast_domain:
    state: present
    broadcast_domain: "{{item.name}}"
    ipspace: Default
    mtu: 1500
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{t_ib_mgmt_vlan_list}}"
  when:
    - inventory_hostname == cluster_name
  tags:
    - ontap_mgmt_broadcast_domain

# Create iSCSI broadcast domain ports with Jumbo frames
- name: TENANT - Create iSCSI broadcast domain ports with Jumbo frames
  netapp.ontap.na_ontap_broadcast_domain:
    state: present
    broadcast_domain: "{{item.name}}"
    ipspace: Default
    mtu: 9000
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{t_storage_vlan_list}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    - inventory_hostname == cluster_name
    - item.storage_protocol == "iSCSI"
  tags:
    - ontap_iscsi_broadcast_domains

# Create NFS broadcast domain ports with Jumbo frames
- name: TENANT - Create NFS broadcast domain ports with Jumbo frames
  netapp.ontap.na_ontap_broadcast_domain:
    state: present
    broadcast_domain: "{{item.name}}"
    ipspace: Default
    mtu: 9000
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{t_storage_vlan_list}}"
  when:
#    - "('nfs' in svm_specs.allowed_protocols)"
    - item.storage_protocol == "NFS"
    - inventory_hostname == cluster_name
  tags:
    - ontap_nfs_broadcast_domain

# Create NVMe/TCP broadcast domain ports with Jumbo frames
- name: TENANT - Create NVMe/TCP broadcast domain ports with Jumbo frames
  netapp.ontap.na_ontap_broadcast_domain:
    state: present
    broadcast_domain: "{{item.name}}"
    ipspace: Default
    mtu: 9000
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{t_storage_vlan_list}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    #    - "('nvme' in svm_specs.allowed_protocols)"
    - item.storage_protocol == "NVMe"
    - inventory_hostname == cluster_name
  tags:
    - ontap_nvme_tcp_broadcast_domains

# Create management vlan interface
- name: TENANT - Create the management vlan interface
  netapp.ontap.na_ontap_net_vlan:
    state: "{{item.1.state}}"
    parent_interface: "{{item.2}}"
    vlanid: "{{item.1.id}}"
    node: "{{item.0.node_name}}"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_ib_mgmt_vlan_list}}"
    - "{{ifgrp_name}}"
  when: 
    - item.1.state == "present"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface
    - inventory_hostname == cluster_name

# Create iSCSI vlans
- name: TENANT - Create the iSCSI vlans
  netapp.ontap.na_ontap_net_vlan:
    state: "{{item.1.state}}"
    parent_interface: "{{item.2}}"
    vlanid: "{{item.1.id}}"
    node: "{{item.0.node_name}}"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "iSCSI"
    - item.1.state == "present"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Create NFS vlans
- name: TENANT - Create the NFS vlans
  netapp.ontap.na_ontap_net_vlan:
    state: "{{item.1.state}}"
    parent_interface: "{{item.2}}"
    vlanid: "{{item.1.id}}"
    node: "{{item.0.node_name}}"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('nfs' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "NFS"
    - item.1.state == "present"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Create NVMe/TCP vlans
- name: TENANT - Create the NVMe/TCP vlans
  netapp.ontap.na_ontap_net_vlan:
    state: "{{item.1.state}}"
    parent_interface: "{{item.2}}"
    vlanid: "{{item.1.id}}"
    node: "{{item.0.node_name}}"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    #    - "('nvme' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "NVMe"
    - item.1.state == "present"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Add the management vlan to the management broadcast domain
- name: TENANT - Adding management vlan to the management broadcast domain
  netapp.ontap.na_ontap_ports:
    state: present
    names: "{{item.0.node_name}}:{{item.2}}-{{item.1.id}}"
    resource_type: "broadcast_domain"
    resource_name: "{{item.1.name}}"
    ipspace: Default
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_ib_mgmt_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Add the iSCSI vlans to the correponding broadcast domains
- name: TENANT - Adding iSCSI-A, iSCSI-B vlans to the corresponding broadcast domains
  netapp.ontap.na_ontap_ports:
    state: present
    names: "{{item.0.node_name}}:{{item.2}}-{{item.1.id}}"
    resource_type: "broadcast_domain"
    resource_name: "{{item.1.name}}"
    ipspace: Default
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "iSCSI"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Add the NFS vlans to the correponding broadcast domains
- name: TENANT - Adding NFS vlans to the corresponding broadcast domains
  netapp.ontap.na_ontap_ports:
    state: present
    names: "{{item.0.node_name}}:{{item.2}}-{{item.1.id}}"
    resource_type: "broadcast_domain"
    resource_name: "{{item.1.name}}"
    ipspace: Default
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true     
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('nfs' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "NFS"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface

# Add the NVMe/TCP vlans to the correponding broadcast domains
- name: TENANT - Adding NVMe-TCP-A, NVMe-TCP-B vlans to the corresponding broadcast domains
  netapp.ontap.na_ontap_ports:
    state: present
    names: "{{item.0.node_name}}:{{item.2}}-{{item.1.id}}"
    resource_type: "broadcast_domain"
    resource_name: "{{item.1.name}}"
    ipspace: Default
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_nested:
    - "{{ ha_pairs | map(attribute='node_specs') | flatten }}"
    - "{{t_storage_vlan_list}}"
    - "{{ifgrp_name}}"
  when:
    #    - "('iscsi' in svm_specs.allowed_protocols)"
    #    - "('nvme' in svm_specs.allowed_protocols)"
    - item.1.storage_protocol == "NVMe"
    - inventory_hostname == cluster_name
  tags:
    - ontap_vlan_interface
