apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-snapclass
driver: csi.trident.netapp.io
deletionPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
allowVolumeExpansion: True
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-nas-eco
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas-economy"
allowVolumeExpansion: True
