---
  # Configuration for Nexus
  #
  # Initiate a configuration backup before making changes. The backup will be
  # stored in the  ~/ directory. Change the directory in ../defaults/main.yml
  #- include_tasks: initiate_nxos_config_backup.yml
  #
  # Configure Features
  - include_tasks: configure_nxos_features.yml
  # Configure VLANs before interfaces when building a tenant
  - include_tasks: configure_nxos_vlans.yml
    when: lan_state | default('present') != 'absent'
  # Configure NTP Distribution Interface Default Gateway
  - include_tasks: configure_default_gw.yml
    when: lan_state | default('present') != 'absent'
  # Configure Interface, Port-Channel and Trunk Settings
  - include_tasks: set_nxos_interfaces.yml
  # Delete VLANs after pruning them from shared trunks when removing a tenant
  - include_tasks: configure_nxos_vlans.yml
    when: lan_state | default('present') == 'absent'
  # Save Configuration
  - include_tasks: save_nxos_config.yml
