---
  # This task Creates required VRF on Nexus switches
  - name: Create VRF 
    cisco.nxos.nxos_vrf:
      name: "{{ tenant_name }}"
      description: "VRF to keep FlexPod safe"
    when: configure_smt != true

  - name: Create VRFs 
    cisco.nxos.nxos_vrf:
      name: "{{ item.vrf }}"
      description: "keep the network safe"
    with_list: "{{ svi_list }}"
    when:  configure_smt == true 
    
