---
- name: "LINUX: Configure Ethernet Adapter Policies"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
  - name: "LINUX: Configure Ethernet Adapter Linux Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: /vnic/EthAdapterPolicies
      query_params:
        $filter: "Name eq '{{ name_of_ethernet_adapter_linux_policy }}'"
      api_body: {
            "Name": "{{ name_of_ethernet_adapter_linux_policy }}",
            "Description": "{{ description_of_ethernet_adapter_linux_policy }}",

            "Organization": {
              "Moid": "{{ intersight_org.api_response.Moid }}"
            },
            Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
            "AdvancedFilter": false,
            "ArfsSettings": {
                "Enabled": false
            },
            "CompletionQueueSettings": {
              "Count": "{{ linux_completion_queue_count }}",
              "RingSize": "{{ linux_completion_ring_size }}"
            },
            "GeneveEnabled": false,
            "InterruptScaling": false,
            "InterruptSettings": {
              "Count": "{{ linux_number_of_interrupts }}",
              "Mode": "MSIx",
              "CoalescingTime": 125,
              "CoalescingType": "MIN"
            },
            "NvgreSettings": {
              "Enabled": false
            },

            "RoceSettings": {
              "Enabled": false
            },
            "RssHashSettings": {
              "ClassId": "vnic.RssHashSettings",
              "Ipv4Hash": true,
              "Ipv6ExtHash": false,
              "Ipv6Hash": true,
              "ObjectType": "vnic.RssHashSettings",
              "TcpIpv4Hash": true,
              "TcpIpv6ExtHash": false,
              "TcpIpv6Hash": true,
              "UdpIpv4Hash": false,
              "UdpIpv6Hash": false
            },
            "RssSettings": false,
            "RxQueueSettings": {
              "Count": "{{ linux_receive_queue_count }}",
              "RingSize": "{{ linux_receive_ring_size }}"
            },
            "TcpOffloadSettings": {
              "TxChecksum": true,
              "RxChecksum": true,
              "LargeSend": true,
              "LargeReceive": true
            },
            "TxQueueSettings": {
              "Count": "{{ linux_transmit_queue_count }}",
              "RingSize": "{{ linux_transmit_ring_size }}"
            },
            "UplinkFailbackTimeout": 5,
            "VxlanSettings": {
              "Enabled": false
            }
        }
    register: ethernet_adapter_linux_policy

  - name: "LINUX: Configure Ethernet Adapter Linux High Traffic Policy"
    cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: /vnic/EthAdapterPolicies
      query_params:
        $filter: "Name eq '{{ name_of_ethernet_adapter_linuxroce_policy }}'"
      api_body: {
            "Name": "{{ name_of_ethernet_adapter_linuxroce_policy }}",
            "Description": "{{ description_of_ethernet_adapter_linuxroce_policy }}",

            "Organization": {
              "Moid": "{{ intersight_org.api_response.Moid }}"
            },
            Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
            "AdvancedFilter": false,
            "ArfsSettings": {
                "Enabled": false
            },
            "CompletionQueueSettings": {
              "Count": "{{ vmht_completion_queue_count }}",
              "RingSize": "{{ vmht_completion_ring_size }}"
            },
            "GeneveEnabled": false,
            "InterruptScaling": false,
            "InterruptSettings": {
              "Count": "{{ vmht_number_of_interrupts }}",
              "Mode": "MSIx",
              "CoalescingTime": 125,
              "CoalescingType": "MIN"
            },
            "NvgreSettings": {
              "Enabled": false
            },

            "RoceSettings": {
              "Enabled": false
            },
            "RssHashSettings": {
              "ClassId": "vnic.RssHashSettings",
              "Ipv4Hash": true,
              "Ipv6ExtHash": false,
              "Ipv6Hash": true,
              "ObjectType": "vnic.RssHashSettings",
              "TcpIpv4Hash": true,
              "TcpIpv6ExtHash": false,
              "TcpIpv6Hash": true,
              "UdpIpv4Hash": false,
              "UdpIpv6Hash": false
            },
            "RssSettings": true,
            "RxQueueSettings": {
              "Count": "{{ vmht_receive_queue_count }}",
              "RingSize": "{{ vmht_receive_ring_size }}"
            },
            "TcpOffloadSettings": {
              "TxChecksum": true,
              "RxChecksum": true,
              "LargeSend": true,
              "LargeReceive": true
            },
            "TxQueueSettings": {
              "Count": "{{ vmht_transmit_queue_count }}",
              "RingSize": "{{ vmht_transmit_ring_size }}"
            },
            "UplinkFailbackTimeout": 5,
            "VxlanSettings": {
              "Enabled": false
            }
        }
    register: ethernet_adapter_linuxroce_policy
