---
#
# VPC configuration on all the port-channels
#
    - name: Enabling vPC on all AFF port-channels
      cisco.nxos.nxos_vpc_interface:
        portchannel: "{{ item.id }}"
        vpc: "{{ item.id }}"
      with_list: "{{ aff_port_channels }}"
